{% set name = "ssh-crypt" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 41d3c651e8b552798d82ea5573a17150005dd516ac71ace8bfa2d5c00ba18d6d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - ssh-crypt = ssh_crypt:main

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - paramiko
    - cryptography

test:
  imports:
    - ssh_crypt
  requires:
    - paramiko
    - cryptography

about:
  home: https://pypi.org/project/ssh-crypt/
  summary: ssh-crypt is a tool to encrypt/decrypt data using your ssh key from ssh-agent
  license: BSD-3-Clause
  license_file: license.txt
  dev_url: https://github.com/Sets88/ssh-crypt

extra:
  recipe-maintainers:
    - cav71
